- name: Prepare Environment for Excel Report Generation
  hosts: web_servers
  tasks:
    - name: Ensure pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install XlsxWriter
      ansible.builtin.pip:
        name: XlsxWriter
        state: present

- name: Check SSSD Configuration and Generate Excel Report
  hosts: web_servers
  tasks:
    - name: Create destination directory for reports
      ansible.builtin.file:
        path: "{{ report_path_remote }}"
        state: directory

    - name: Check SSSD configuration
      ansible.builtin.shell: "grep -i '^simple_allow_groups' /etc/sssd/sssd.conf | cut -d' ' -f3"
      register: sssd_check_result
      ignore_errors: yes

    - name: Generate Excel report for SSSD configuration
      ansible.builtin.command: "python3 generate_sssd_report_excel.py '{{ ansible_hostname }}' '{{ 'Config OK' if sssd_check_result.rc == 0 else 'Config Error' }}' '{{ sssd_check_result.stdout | default('N/A') }}'"
      delegate_to: localhost
      run_once: true

- name: Synchronize Excel Reports to Local Machine
  hosts: web_servers
  tasks:
    - name: Synchronize Excel reports to the local machine
      ansible.builtin.synchronize:
        src: "{{ report_path_remote }}"
        dest: "{{ report_path_local }}"
        mode: pull

- name: Commit Excel Reports to Git Repository
  hosts: localhost
  tasks:
    - name: Add Excel reports to Git
      ansible.builtin.command:
        cmd: "git add ."
        args:
          chdir: "{{ report_path_local }}"
      ignore_errors: yes

    - name: Commit Excel reports to Git
      ansible.builtin.command:
        cmd: "git commit -m 'Automatic update Excel Report'"
        args:
          chdir: "{{ report_path_local }}"
      ignore_errors: yes

    - name: Push Excel reports to Git
      ansible.builtin.command:
        cmd: "git push origin main"
        args:
          chdir: "{{ report_path_local }}"
      ignore_errors: yes
