- name: Setup Environment for Excel Report Generation
  hosts: web_servers
  become: yes
  tasks:
    - name: Determine RHEL version and appropriate Python interpreter
      set_fact:
        is_rhel_8_or_later: "{{ ansible_facts['distribution_major_version'] | int >= 8 }}"

    - name: Install Python3 and pip for RHEL 7 using yum
      yum:
        name:
          - python36
          - python36-pip
        state: present
      when: not is_rhel_8_or_later

    - name: Install Python3 and pip for RHEL 8 or later using dnf
      dnf:
        name:
          - python3
          - python3-pip
        state: present
      when: is_rhel_8_or_later

    - name: Install XlsxWriter using pip3
      pip:
        name: XlsxWriter
        executable: pip3

- name: Generate Excel Report for Each Host
  hosts: web_servers
  gather_facts: false
  tasks:
    - name: Check SSSD configuration
      shell: "grep -i '^simple_allow_groups' /etc/sssd/sssd.conf | cut -d' ' -f3"
      register: sssd_check_result
      ignore_errors: yes

    - name: Generate Excel report for SSSD configuration using Python script
      local_action:
        module: command
        cmd: "python3 /root/ssdreport/generate_sssd_report_excel.py '{{ inventory_hostname }}' '{{ sssd_check_result.stdout | default('N/A') }}'"
      run_once: false


- name: Synchronize CSV reports to the local machine
  hosts: web_servers
  gather_facts: false
  tasks:
    - name: Synchronize CSV reports to the local machine
      ansible.builtin.synchronize:
        mode: pull
        src: "{{ report_path_remote }}"
        dest: "{{ report_path_local }}"
        recursive: yes

- name: Commit CSV reports to Git repository
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add CSV reports to Git
      ansible.builtin.command:
        cmd: "git add ."
      args:
        chdir: "{{ report_path_local }}"
      ignore_errors: yes

    - name: Commit CSV reports to Git
      ansible.builtin.command:
        cmd: "git commit -m 'Automatic update CSV Report'"
      args:
        chdir: "{{ report_path_local }}"
      ignore_errors: yes

    - name: Push CSV reports to Git
      ansible.builtin.command:
        cmd: "git push origin main"
      args:
        chdir: "{{ report_path_local }}"
      ignore_errors: yes
